name: Current Date Example

on:
  workflow_dispatch

jobs:
  print_date:
    env:
      CURRENT_DATE: $(date +'%Y-%m-%d')
      START_OF_MONTH: $(date +'%Y-%m-%1')
    runs-on: ubuntu-latest
    steps:        
      - name: Display date from env
        run: echo "Current date is ${{ env.CURRENT_DATE }}"
        
      - name: Display Month start from env
        run: | 
             echo "Current Month beginning at : ${{ env.START_OF_MONTH }}"
