name: Current Date Example

on:
  push:
    branches:
      - main

jobs:
  print_date:
    env:
     current-date: $(date +'%Y-%m-%d')
    runs-on: ubuntu-latest
    steps:
      - name: Set Current Date as Environment Variable
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Display Current Date
        run: echo "The current date is $CURRENT_DATE"
        
      - name: Display date from env
        run: echo "Current date is ${{ env.current-date }}"
