name: Echo Current Date

on:
  push:
    branches:
      - main

jobs:
  echo_date:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Date
        id: get_date
        run: echo "date=$(date +'%Y-%m-%d')"
        shell: bash

      - name: Echo Current Date
        run: echo "The current date is ${{ steps.get_date.outputs.date }}"
