name: Current Date Example

on:
  push:
    branches:
      - main

jobs:
  print_date:
    env:
      current-date: $(date +'%Y-%m-%d')
      start-month: $(date -d "$(date +'%Y-%m-01') - 1 day" +'%Y-%m-%d')
    runs-on: ubuntu-latest
    steps:        
      - name: Display date from env
        run: echo "Current date is ${{ env.current-date }}"
        
      - name: Display Month start from env
        run: echo "Month starts at ${{ env.start-month }}"
