name: Ten Minute Echo

on:
  workflow_dispatch

jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "This message will be echoed every ten minutes."
