name: Pull Request Approval
on:
  pull_request_review:
    types:
        - submitted
        - edited
        - dismissed
jobs:
  check_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request is approved
        uses: actions/github-script@v4
        with:
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const approvedByUser = 'shayan-shaikh';
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const approvalExists = reviews.some(review => review.user.login === approvedByUser && review.state === 'APPROVED');
            if (!approvalExists) {
              core.setFailed('Pull request requires approval from ' + approvedByUser);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}






