name: Pull Request Approval
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
jobs:
  check_approval:
    runs-on: ubuntu-latest
    env:
      approvedByUser: 'shayan-shaikh'
    steps:
      - name: Check if pull request is approved
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const mostRecentReview = reviews
              .filter(review => review.user.login === process.env.approvedByUser && review.state === 'APPROVED')
              .sort((a, b) => new Date(b.submitted_at) - new Date(a.submitted_at))
              .shift();

            if (!mostRecentReview) {
              core.setFailed('Pull request requires approval from ' + process.env.approvedByUser);
            }
