name: Pull Request Approval
on:
  pull_request:
    types:
      - opened
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
jobs:
  check_approval:
    runs-on: ubuntu-latest
    env:
      approvedByUser: 'shayan-shaikh'
    steps:
      - name: Check if pull request is approved
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const latestReview = reviews.reduce((prev, current) => (new Date(prev.submitted_at) > new Date(current.submitted_at)) ? prev : current);

            if (!latestReview) {
              core.setFailed('Pull request requires approval from ' + process.env.approvedByUser);
            } else if (latestReview.user.login === process.env.approvedByUser && latestReview.state === 'APPROVED') {
              console.log('Pull request is approved by ' + process.env.approvedByUser);
            } else {
              core.setFailed('Pull request requires approval from ' + process.env.approvedByUser);
            }
