name: API Status Action

on:
  workflow_dispatch

jobs:
  get_api_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make API call and display status
        id: get_status
        run: |
          curl -X GET "https://valorant-api.com/v1/bundles/d958b181-4e7b-dc60-7c3c-e3a3a376a8d2" >> test.json
          response = $(cat test.json)
          echo "Current date and time during the run : $(date)"
          status = $(echo "$response" | jq -r '.status') >> 'GITHUB_OUTPUT'
          echo $status

          
      - name: Display status
        run: echo " ${{ steps.get_status.outputs.status }}"
