name: Fetch Endpoint and Save to JSON

on:
  push:
    branches:
      - main

jobs:
  fetch_endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Endpoint and Save to JSON
        id: fetch_endpoint
        run: |
          curl -X GET "https://valorant-api.com/v1/bundles/d958b181-4e7b-dc60-7c3c-e3a3a376a8d2" > result.json

      - name: Save Status to Output
        run: |
          status=$(jq -r '.status' result.json)
          echo "::set-output name=status::$status"
        id: save_status_output
      
      - name: Display Endpoint Status
        run: |
          status=${{ needs.fetch_endpoint.outputs.status }}
          echo "Endpoint Status: $status"
