name: OpenAI Billing Alerts
on:
  workflow_dispatch 
  #Disabling cron scheduling for now for testing
jobs:
  send_email_alerts:
    environment: staging
    env:
      CURRENT_DATE: $(date +'%Y-%m-%d')
      START_OF_MONTH: $(date +'%Y-%m-01')
      CURRENT_MONTH: $(date +'%B')
      domain: dev
    runs-on: ubuntu-latest
    outputs:
      usage_for_month: ${{ steps.get_usage.outputs.usage_for_month }}
    steps:
      - name: Fetch OpenAI API Usage
        run: |
           curl -X GET "https://valorant-api.com/v1/bundles/d958b181-4e7b-dc60-7c3c-e3a3a376a8d2" >> test.json

      - name: Construct Email body from the API response
        id: get_usage
        run: |
          const fs = require('fs');
          const jsonFile = fs.readFileSync('test.json');
          const data = JSON.parse(jsonFile);
          const total_usage = data.status;
          console.log(`total_usage=${total_usage}`); >> $GITHUB_OUTPUT
      
      - name: Send Email
        run: echo ${{ needs.send_email_alerts.outputs.usage_for_month }}
