name: Display Current and Yesterday's Dates

on:
  push:
    branches:
      - main

jobs:
  display_dates:
    runs-on: ubuntu-latest
    env:
      current-date: ''
      previous-date: ''
    steps:
      - name: Set Current Date
        run: |
          export current-date=$(date +'%Y-%m-%d')
          echo "current-date=$current-date" >> $GITHUB_ENV

      - name: Set Yesterday's Date
        run: |
          export previous-date=$(date -d "yesterday" +'%Y-%m-%d')
          echo "previous-date=$previous-date" >> $GITHUB_ENV

      - name: Display Dates
        run: |
          echo "Current Date: $current-date"
          echo "Yesterday's Date: $previous-date"
