name: Display Current and Yesterday's Dates

on:
  workflow_dispatch

jobs:
  display_dates:
    runs-on: ubuntu-latest
    env:
      CURRENT_DATE: ''
      YESTERDAY_DATE: ''
    steps:
      - name: Set Current Date
        run: |
          export CURRENT_DATE=$(date +'%Y-%m-%d')
          echo "CURRENT_DATE=$CURRENT_DATE" >> $GITHUB_ENV

      - name: Set Yesterday's Date
        run: |
          export YESTERDAY_DATE=$(date -d "yesterday" +'%Y-%m-%d')
          echo "YESTERDAY_DATE=$YESTERDAY_DATE" >> $GITHUB_ENV

      - name: Display Dates
        run: |
          echo "Current Date: $CURRENT_DATE"
          echo "Yesterday's Date: $YESTERDAY_DATE"
